name: WSO2 API CI/CD
on:
  push:
    paths:
      - 'apim/AirlineProductAPI/**'
      - '.github/workflows/airline-api-pipeline.yml'
    branches:
      - prod

jobs:
  deploy-api-prod:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'prod') || github.event_name == 'push' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add etc/hosts entry for airbus.am.wso2.com 🌐
        run: |
          # Format: IP Address    Hostname(s)
          # 'tee -a' appends the line to /etc/hosts using sudo privileges.
          echo '135.235.250.243 airbus.am.wso2.com' | sudo tee -a /etc/hosts
          
          # Optional: Verify the entry
          echo "Hosts file content after addition:"
          cat /etc/hosts

      - name: Install apictl
        run: |
          wget https://github.com/wso2/product-apim-tooling/releases/download/v4.6.0/apictl-4.6.0-linux-amd64.tar.gz
          tar -xzf apictl-4.6.0-linux-amd64.tar.gz
          chmod +x apictl/apictl
          sudo mv apictl/apictl /usr/local/bin/

      - name: Add Prod Environment
        run: |
          apictl add env prod --apim https://${{ secrets.WSO2_APIM }}

      - name: Login to Prod
        run: |
          apictl login prod -u ${{ secrets.APIM_USERNAME }} -p ${{ secrets.APIM_PASSWORD }} --insecure

      - name: Import API to Prod
        run: |
          apictl import api -f apim/AirlineProductAPI/ -e prod --preserve-provider=false --update --insecure 

      - name: Run Tests (Optional)
        run: |
          apictl get apis -e prod --insecure | awk 'NR>1 {print}' | grep -E "AirlineProductAPI" || {
            echo "AirlineProductAPI not found in Publisher (prod)."
            exit 1
          }
          echo "AirlineProductAPI is present in Publisher (prod)"